# Generated by Django 6.0.3 on 2026-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('TEMP', 'Temporary'), ('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='TEMP', max_length=10),
        ),
    ]
